#!/usr/bin/env python3
"""
Generate an animated, theme-matched projects panel (projects.svg).

Reads merged.json generated by fetch_data.py and creates:
- 1180px wide two-column project cards
- Animated card entrance
- Animated borders
- Project logos
- Technology pills
- GitHub stars
- Last updated time
- Language distribution donut
- Dark + light SVG versions

Designed for SaifAK45's GitHub profile.
"""

import json
import base64
import os
import sys
import math
import html
from datetime import datetime, timezone


# ============================================================
# THEMES
# ============================================================

THEMES = {
    "dark": {
        "BG": "#0A101F",
        "PANEL": "#0C1426",
        "PANEL_BAR": "#0B1222",

        "CYAN": "#22D3EE",
        "VIOLET": "#A78BFA",
        "VIOLET2": "#7C3AED",
        "EMERALD": "#10B981",

        "TEXT": "#F8FAFC",
        "MUTED": "#94A3B8",
        "DIM": "#475569",

        "STROKE": "rgba(34,211,238,0.28)",
        "STROKE_HI": "rgba(34,211,238,0.5)",
        "STROKE_LO": "rgba(34,211,238,0.22)",

        "BARLINE": "rgba(255,255,255,0.08)",
        "RING_BG": "rgba(148,163,184,0.15)",

        "PILL_BG": "rgba(124,58,237,0.28)",
        "PILL_STROKE": "rgba(167,139,250,0.5)",

        "MONO_TX": "#EDE9FE",
    },

    "light": {
        "BG": "#F8FAFC",
        "PANEL": "#FFFFFF",
        "PANEL_BAR": "#F1F5F9",

        "CYAN": "#0891B2",
        "VIOLET": "#7C3AED",
        "VIOLET2": "#7C3AED",
        "EMERALD": "#059669",

        "TEXT": "#0F172A",
        "MUTED": "#475569",
        "DIM": "#94A3B8",

        "STROKE": "rgba(8,145,178,0.30)",
        "STROKE_HI": "rgba(8,145,178,0.55)",
        "STROKE_LO": "rgba(8,145,178,0.20)",

        "BARLINE": "rgba(0,0,0,0.08)",
        "RING_BG": "rgba(100,116,139,0.20)",

        "PILL_BG": "rgba(124,58,237,0.12)",
        "PILL_STROKE": "rgba(124,58,237,0.4)",

        "MONO_TX": "#FFFFFF",
    },
}


# ============================================================
# ACTIVE THEME VARIABLES
# ============================================================

BG = PANEL = PANEL_BAR = CYAN = VIOLET = VIOLET2 = None
EMERALD = TEXT = MUTED = DIM = None

STROKE = STROKE_HI = STROKE_LO = None
BARLINE = RING_BG = PILL_BG = PILL_STROKE = None
MONO_TX = None

DONUT_COLORS = []


def set_theme(name):
    """Apply theme variables globally."""
    theme = THEMES[name]
    g = globals()

    for key, value in theme.items():
        g[key] = value

    g["DONUT_COLORS"] = [
        theme["VIOLET"],
        theme["CYAN"],
        theme["EMERALD"],
        "#6366F1",
        "#64748B",
        "#94A3B8",
    ]


set_theme("dark")


# ============================================================
# LAYOUT
# ============================================================

W = 1180

CARD_W = 578
CARD_H = 176

GAP = 14
MARGIN = 5

FONT = (
    "ui-monospace,SFMono-Regular,Menlo,Consolas,"
    "'Liberation Mono',monospace"
)


# ============================================================
# HELPERS
# ============================================================

def esc(value):
    """Escape text for safe SVG output."""
    return html.escape(str(value), quote=True)


def rel_time(iso):
    """Convert GitHub pushed_at timestamp into a readable relative time."""
    if not iso:
        return "n/a"

    try:
        dt = datetime.fromisoformat(
            iso.replace("Z", "+00:00")
        )

        delta = datetime.now(timezone.utc) - dt

        if delta.days > 365:
            return f"{delta.days // 365}y ago"

        if delta.days > 30:
            return f"{delta.days // 30}mo ago"

        if delta.days > 0:
            return f"{delta.days}d ago"

        hours = delta.seconds // 3600

        if hours:
            return f"{hours}h ago"

        return "just now"

    except Exception:
        return "n/a"


# ============================================================
# LOGO LOADER
# ============================================================

def load_logo_b64(path):
    """
    Load PNG/JPG/JPEG/SVG/WEBP logos and convert them to
    base64 data URIs for embedding directly into the SVG.
    """

    if not path:
        return None

    # Supports both:
    # logos/file.png
    # file.png
    possible_paths = [
        os.path.join("logos", path),
        os.path.join(".", path),
    ]

    for logo_path in possible_paths:

        if not os.path.exists(logo_path):
            continue

        extension = os.path.splitext(logo_path)[1].lower()

        mime_types = {
            ".png": "image/png",
            ".jpg": "image/jpeg",
            ".jpeg": "image/jpeg",
            ".svg": "image/svg+xml",
            ".webp": "image/webp",
        }

        mime = mime_types.get(
            extension,
            "image/png"
        )

        try:
            with open(logo_path, "rb") as file:
                encoded = base64.b64encode(
                    file.read()
                ).decode()

            return f"data:{mime};base64,{encoded}"

        except Exception as error:
            print(
                f"warning: could not load logo {logo_path}: {error}",
                file=sys.stderr,
            )

    print(
        f"warning: logo not found: {path}",
        file=sys.stderr,
    )

    return None


# ============================================================
# TEXT WRAPPING
# ============================================================

def wrap_text(text, max_chars, max_lines=2):
    """Wrap text without allowing it to overflow the card."""

    words = str(text or "").split()

    lines = []
    current = ""

    for word in words:

        candidate = (
            f"{current} {word}".strip()
        )

        if len(candidate) <= max_chars:
            current = candidate

        else:
            if current:
                lines.append(current)

            current = word

            if len(lines) == max_lines:
                break

    if current and len(lines) < max_lines:
        lines.append(current)

    if len(lines) == max_lines:

        original_words = len(words)
        rendered_words = sum(
            len(line.split())
            for line in lines
        )

        if rendered_words < original_words:

            last = lines[-1]

            lines[-1] = (
                last[:max_chars - 1].rstrip()
                + "…"
            )

    return lines


# ============================================================
# LANGUAGE DONUT
# ============================================================

def donut_segments(
    languages,
    cx,
    cy,
    radius,
    begin,
):
    """
    Create animated language donut segments.
    """

    total = sum(languages.values()) or 1

    entries = sorted(
        languages.items(),
        key=lambda item: -item[1],
    )[:4]

    other = total - sum(
        value for _, value in entries
    )

    if other > 0:
        entries.append(
            ("Other", other)
        )

    circumference = (
        2 * math.pi * radius
    )

    output = []
    legend = []

    offset = 0.0
    start_time = begin

    for index, (language, value) in enumerate(entries):

        fraction = value / total
        segment = fraction * circumference

        color = DONUT_COLORS[
            index % len(DONUT_COLORS)
        ]

        output.append(
            f'<circle '
            f'cx="{cx}" '
            f'cy="{cy}" '
            f'r="{radius}" '
            f'fill="none" '
            f'stroke="{color}" '
            f'stroke-width="9" '
            f'stroke-dasharray="{segment:.2f} {circumference - segment:.2f}" '
            f'stroke-dashoffset="{-offset:.2f}" '
            f'transform="rotate(-90 {cx} {cy})" '
            f'opacity="0">'
            
            f'<animate '
            f'attributeName="opacity" '
            f'from="0" '
            f'to="1" '
            f'dur="0.01s" '
            f'begin="{start_time:.2f}s" '
            f'fill="freeze"/>'

            f'<animate '
            f'attributeName="stroke-dasharray" '
            f'from="0 {circumference:.2f}" '
            f'to="{segment:.2f} {circumference - segment:.2f}" '
            f'dur="0.6s" '
            f'begin="{start_time:.2f}s" '
            f'fill="freeze" '
            f'calcMode="spline" '
            f'keyTimes="0;1" '
            f'keySplines="0.3 0 0.2 1"/>'

            f'</circle>'
        )

        legend.append(
            (
                language,
                fraction,
                color,
            )
        )

        offset += segment
        start_time += 0.18

    return "".join(output), legend


# ============================================================
# PROJECT CARD
# ============================================================

def card(project, x, y, index):

    begin = 0.25 + index * 0.15

    elements = []
    add = elements.append

    # --------------------------------------------------------
    # Repository link
    # --------------------------------------------------------

    repo = str(
        project.get("repo", "")
    ).strip()

    repo = (
        repo
        .replace(
            "https://github.com/",
            "",
        )
        .replace(
            "http://github.com/",
            "",
        )
        .rstrip("/")
    )

    href = (
        f"https://github.com/{esc(repo)}"
    )

    add(
        f'<a href="{href}" target="_blank">'
    )

    add(
        f'<g opacity="0" '
        f'transform="translate({x},{y})">'
    )

    # Card entrance animation
    add(
        f'<animate '
        f'attributeName="opacity" '
        f'from="0" '
        f'to="1" '
        f'dur="0.5s" '
        f'begin="{begin:.2f}s" '
        f'fill="freeze"/>'
    )

    # --------------------------------------------------------
    # Card shell
    # --------------------------------------------------------

    add(
        f'<rect '
        f'width="{CARD_W}" '
        f'height="{CARD_H}" '
        f'rx="12" '
        f'fill="{PANEL}" '
        f'stroke="{STROKE}">'
        
        f'<animate '
        f'attributeName="stroke" '
        f'values="{STROKE_LO};{STROKE_HI};{STROKE_LO}" '
        f'dur="4.5s" '
        f'begin="{begin + index * 0.7:.2f}s" '
        f'repeatCount="indefinite"/>'

        f'</rect>'
    )

    # Terminal header
    add(
        f'<rect '
        f'width="{CARD_W}" '
        f'height="30" '
        f'rx="12" '
        f'fill="{PANEL_BAR}"/>'
    )

    add(
        f'<rect '
        f'y="18" '
        f'width="{CARD_W}" '
        f'height="12" '
        f'fill="{PANEL_BAR}"/>'
    )

    add(
        f'<line '
        f'x1="0" '
        f'y1="30" '
        f'x2="{CARD_W}" '
        f'y2="30" '
        f'stroke="{BARLINE}"/>'
    )

    # Repository path
    add(
        f'<text '
        f'x="16" '
        f'y="19" '
        f'font-size="10" '
        f'fill="{MUTED}">'
        f'<tspan fill="{CYAN}">&#8226;</tspan> '
        f'{esc(repo)}'
        f'</text>'
    )

    # --------------------------------------------------------
    # Activity indicator
    # --------------------------------------------------------

    days = 999

    try:
        pushed_at = project.get(
            "pushed_at",
            "",
        )

        if pushed_at:

            dt = datetime.fromisoformat(
                pushed_at.replace(
                    "Z",
                    "+00:00",
                )
            )

            days = (
                datetime.now(timezone.utc)
                - dt
            ).days

    except Exception:
        pass

    if days <= 14:

        add(
            f'<circle '
            f'cx="{CARD_W - 16}" '
            f'cy="15" '
            f'r="3.5" '
            f'fill="{EMERALD}">'

            f'<animate '
            f'attributeName="opacity" '
            f'values="1;0.25;1" '
            f'dur="1.8s" '
            f'repeatCount="indefinite"/>'

            f'</circle>'
        )

    else:

        add(
            f'<circle '
            f'cx="{CARD_W - 16}" '
            f'cy="15" '
            f'r="3.5" '
            f'fill="{DIM}"/>'
        )

    # --------------------------------------------------------
    # Logo
    # --------------------------------------------------------

    logo = project.get(
        "_logo_b64"
    )

    float_animation = (
        f'<animateTransform '
        f'attributeName="transform" '
        f'type="translate" '
        f'values="0 0; 0 -2.5; 0 0" '
        f'dur="5s" '
        f'begin="{begin + index * 0.5:.2f}s" '
        f'repeatCount="indefinite" '
        f'calcMode="spline" '
        f'keyTimes="0;0.5;1" '
        f'keySplines="0.4 0 0.6 1;0.4 0 0.6 1"/>'
    )

    if logo:

        add(
            f'<g>'
            f'{float_animation}'
            f'<image '
            f'x="16" '
            f'y="44" '
            f'width="40" '
            f'height="40" '
            f'href="{logo}" '
            f'preserveAspectRatio="xMidYMid meet"/>'
            f'</g>'
        )

    else:

        initial = esc(
            (
                project.get(
                    "name",
                    "?",
                )
                or "?"
            )[0].upper()
        )

        add(
            f'<g>'
            f'{float_animation}'

            f'<rect '
            f'x="16" '
            f'y="44" '
            f'width="40" '
            f'height="40" '
            f'rx="9" '
            f'fill="{VIOLET2}" '
            f'opacity="0.9"/>'

            f'<text '
            f'x="36" '
            f'y="71" '
            f'text-anchor="middle" '
            f'font-size="20" '
            f'font-weight="700" '
            f'fill="{MONO_TX}">'
            f'{initial}'
            f'</text>'

            f'</g>'
        )

    # --------------------------------------------------------
    # Project name
    # --------------------------------------------------------

    name = esc(
        project.get(
            "name",
            "unnamed",
        )
    )

    add(
        f'<text '
        f'x="68" '
        f'y="61" '
        f'font-size="17" '
        f'font-weight="700" '
        f'fill="{TEXT}">'
        f'{name}'

        f'<tspan fill="{CYAN}">_'
        f'<animate '
        f'attributeName="opacity" '
        f'values="1;0;1" '
        f'dur="1.2s" '
        f'begin="{begin + 0.4:.2f}s" '
        f'repeatCount="indefinite"/>'
        f'</tspan>'

        f'</text>'
    )

    # --------------------------------------------------------
    # Description
    # --------------------------------------------------------

    description_lines = wrap_text(
        project.get(
            "description",
            "",
        ),
        43,
        max_lines=2,
    )

    for line_index, line in enumerate(
        description_lines
    ):

        add(
            f'<text '
            f'x="68" '
            f'y="{80 + line_index * 16}" '
            f'font-size="11" '
            f'fill="{MUTED}">'
            f'{esc(line)}'
            f'</text>'
        )

    # --------------------------------------------------------
    # Technology pills
    # --------------------------------------------------------

    tags = (
        project.get("tags")
        or []
    )[:4]

    tag_x = 68
    tag_y = 118

    for tag in tags:

        tag_width = (
            len(str(tag)) * 6.2
            + 14
        )

        # Don't allow pills to reach the donut area
        if (
            tag_x + tag_width
            > CARD_W - 145
        ):
            break

        add(
            f'<rect '
            f'x="{tag_x}" '
            f'y="{tag_y}" '
            f'width="{tag_width:.0f}" '
            f'height="17" '
            f'rx="8.5" '
            f'fill="{PILL_BG}" '
            f'stroke="{PILL_STROKE}"/>'
        )

        add(
            f'<text '
            f'x="{tag_x + tag_width / 2:.0f}" '
            f'y="{tag_y + 12:.0f}" '
            f'text-anchor="middle" '
            f'font-size="9.2" '
            f'fill="{VIOLET}">'
            f'{esc(tag)}'
            f'</text>'
        )

        tag_x += (
            tag_width + 7
        )

    # --------------------------------------------------------
    # Bottom row
    # --------------------------------------------------------

    stars = project.get(
        "stars",
        0,
    )

    add(
        f'<text '
        f'x="68" '
        f'y="{CARD_H - 13}" '
        f'font-size="11" '
        f'fill="{MUTED}">'

        f'<tspan fill="{CYAN}">'
        f'&#9733;'
        f'</tspan> '

        f'{stars}'

        f'<tspan '
        f'fill="{DIM}" '
        f'dx="14">'
        f'updated '
        f'{rel_time(project.get("pushed_at"))}'
        f'</tspan>'

        f'</text>'
    )

    # --------------------------------------------------------
    # Language donut
    # --------------------------------------------------------

    languages = (
        project.get("languages")
        or {}
    )

    if languages:

        cx = CARD_W - 58
        cy = CARD_H // 2 + 6
        radius = 27

        segments, legend = donut_segments(
            languages,
            cx,
            cy,
            radius,
            begin + 0.3,
        )

        # Donut background
        add(
            f'<circle '
            f'cx="{cx}" '
            f'cy="{cy}" '
            f'r="{radius}" '
            f'fill="none" '
            f'stroke="{RING_BG}" '
            f'stroke-width="9"/>'
        )

        add(segments)

        # Main percentage
        if legend:

            top_language = legend[0]

            add(
                f'<text '
                f'x="{cx}" '
                f'y="{cy + 4}" '
                f'text-anchor="middle" '
                f'font-size="11" '
                f'font-weight="700" '
                f'fill="{TEXT}">'
                f'{top_language[1] * 100:.0f}%'
                f'</text>'
            )

        # Language legend
        dot_x = cx - radius - 92
        text_x = dot_x + 9
        legend_y = cy - 22

        for (
            language,
            fraction,
            color,
        ) in legend[:3]:

            add(
                f'<circle '
                f'cx="{dot_x}" '
                f'cy="{legend_y}" '
                f'r="3.5" '
                f'fill="{color}"/>'
            )

            add(
                f'<text '
                f'x="{text_x}" '
                f'y="{legend_y + 4}" '
                f'font-size="10" '
                f'fill="{MUTED}">'
                f'{esc(language)} '
                f'{fraction * 100:.0f}%'
                f'</text>'
            )

            legend_y += 18

    # Close card group + link
    add("</g>")
    add("</a>")

    return "".join(elements)


# ============================================================
# BUILD SVG
# ============================================================

def build(projects, theme="dark"):

    rows = math.ceil(
        len(projects) / 2
    )

    height = (
        56
        + rows * (CARD_H + GAP)
        + MARGIN
    )

    gradient_id = (
        f"accent_{theme}"
    )

    output = []
    add = output.append

    # SVG root
    add(
        f'<svg '
        f'xmlns="http://www.w3.org/2000/svg" '
        f'width="{W}" '
        f'height="{height}" '
        f'viewBox="0 0 {W} {height}" '
        f'font-family="{FONT}" '
        f'role="img" '
        f'aria-label="Projects">'
    )

    # Background
    add(
        f'<rect '
        f'width="{W}" '
        f'height="{height}" '
        f'fill="{BG}"/>'
    )

    # --------------------------------------------------------
    # Animated gradient
    # --------------------------------------------------------

    add(
        f'<defs>'

        f'<linearGradient '
        f'id="{gradient_id}" '
        f'x1="0" '
        f'y1="0" '
        f'x2="1" '
        f'y2="0">'

        f'<stop '
        f'offset="0" '
        f'stop-color="{VIOLET2}">'

        f'<animate '
        f'attributeName="stop-color" '
        f'values="{VIOLET2};{CYAN};{EMERALD};{VIOLET2}" '
        f'dur="10s" '
        f'repeatCount="indefinite"/>'

        f'</stop>'

        f'<stop '
        f'offset="1" '
        f'stop-color="{EMERALD}">'

        f'<animate '
        f'attributeName="stop-color" '
        f'values="{EMERALD};{VIOLET2};{CYAN};{EMERALD}" '
        f'dur="10s" '
        f'repeatCount="indefinite"/>'

        f'</stop>'

        f'</linearGradient>'

        f'</defs>'
    )

    # --------------------------------------------------------
    # Header
    # --------------------------------------------------------

    add(
        f'<text '
        f'x="{MARGIN + 2}" '
        f'y="18" '
        f'font-size="11" '
        f'letter-spacing="2" '
        f'fill="{CYAN}">'
        f'PROJECTS.LIST'
        f'</text>'
    )

    add(
        f'<text '
        f'x="{MARGIN + 130}" '
        f'y="18" '
        f'font-size="10" '
        f'fill="{DIM}">'
        f'./projects.sh --all'
        f'</text>'
    )

    add(
        f'<line '
        f'x1="{MARGIN}" '
        f'y1="28" '
        f'x2="{W - MARGIN}" '
        f'y2="28" '
        f'stroke="url(#{gradient_id})" '
        f'stroke-width="1.5" '
        f'opacity="0.7"/>'
    )

    # --------------------------------------------------------
    # Cards
    # --------------------------------------------------------

    for index, project in enumerate(
        projects
    ):

        x = (
            MARGIN
            + (index % 2)
            * (CARD_W + GAP + 4)
        )

        y = (
            42
            + (index // 2)
            * (CARD_H + GAP)
        )

        add(
            card(
                project,
                x,
                y,
                index,
            )
        )

    add("</svg>")

    return "".join(output)


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    source = (
        sys.argv[1]
        if len(sys.argv) > 1
        else "merged.json"
    )

    output_directory = (
        sys.argv[2]
        if len(sys.argv) > 2
        else "."
    )

    # Load merged GitHub data
    with open(source, "r", encoding="utf-8") as file:
        projects = json.load(file)

    # Load project logos
    for project in projects:

        project["_logo_b64"] = (
            load_logo_b64(
                project.get("logo")
            )
        )

    # Generate both themes
    for theme, filename in (
        ("dark", "projects.svg"),
        ("light", "projects-light.svg"),
    ):

        set_theme(theme)

        svg = build(
            projects,
            theme,
        )

        output_path = os.path.join(
            output_directory,
            filename,
        )

        with open(
            output_path,
            "w",
            encoding="utf-8",
        ) as file:

            file.write(svg)

        print(
            f"wrote {output_path}: "
            f"{theme}, "
            f"{len(projects)} projects, "
            f"{len(svg) // 1024}KB"
        )